export const stacks = {
  'Cloud platforms': {description:'Cloud-native foundations for secure, scalable enterprise workloads.',items:['AWS','Azure','GCP','Amazon EKS','Terraform','Kubernetes']},
  'Lakehouse & modeling': {description:'Trusted data foundations, from ingestion to analytics-ready products.',items:['Databricks','Delta Lake','Snowflake','dbt','Data Vault 2.0','Kimball Modeling']},
  'Real-time integration': {description:'Resilient event processing with recovery, replay and observability.',items:['Apache Kafka','Debezium CDC','Apache Flink','Spark Structured Streaming','Airflow','Python / SQL']},
  'Governance & AI': {description:'Permission-aware access that connects enterprise data with AI workloads.',items:['Unity Catalog','Collibra','OpenLineage','LangChain / LangGraph','MCP','Snowflake Cortex']}
};
export const career = [
 {company:'Omnicell',role:'Data Solution Architect',date:'Jan 2023 — Present',body:'Leading cloud-native healthcare data architecture, from requirements and reference architectures through production rollout. Architected a governed Patient 360 foundation and provided technical direction to 4–5 data engineers.',tags:['Patient 360','Databricks','Governance']},
 {company:'NICE',role:'Senior Data Engineer',date:'May 2020 — Dec 2022',body:'Built batch and real-time pipelines across five financial domains. Delivered resilient streaming, incremental Delta Lake processing, auditable data models and production reliability practices.',tags:['Kafka','Spark','Delta Lake']},
 {company:'Banner Health',role:'Cloud Engineer',date:'Jan 2017 — Apr 2020',body:'Modernized a B2B SaaS environment on Amazon EKS. Developed reusable Terraform modules across six infrastructure domains and automated delivery with security, recovery and operational controls.',tags:['AWS / Azure','Terraform','Kubernetes']},
 {company:'PBG',role:'ETL & Data Warehouse Engineer',date:'Jan 2014 — Dec 2016',body:'Consolidated operational data from 6+ source types. Built incremental pipelines, dimensional models across 8+ business entities and reconciliation controls for trusted financial reporting.',tags:['Python / SQL','ETL / CDC','Dimensional modeling']}
];
export const projects = [
 {id:'patient',kind:'HEALTHCARE • LAKEHOUSE',title:'Patient 360 Lakehouse',intro:'A governed longitudinal patient record across fragmented healthcare systems.',metric:'6+',metricLabel:'healthcare domains',nodes:['EHR / FHIR / Claims','Patient identity','Governed lakehouse','Analytics / AI'],problem:'Patient information was fragmented across clinical and operational systems, with inconsistent identities and definitions.',work:'Architected a Patient 360 lakehouse integrating Epic, Cerner, FHIR, X12 EDI, claims, medication, laboratory, patient, encounter and provider data. Established canonical models, data contracts and EMPI/MRN identity resolution.',result:'Enabled interoperability, enterprise analytics, AI/ML and reusable data products from a consistent patient-data foundation. Extended the platform into predictive-care and permission-aware RAG workflows.',controls:'HIPAA/HITRUST-aligned architecture with least-privilege access, masking, encryption, lineage and auditability.',tags:['Databricks','Spark','Python','SQL'],source:'Experience · Omnicell'},
 {id:'cdc',kind:'STREAMING • ENTERPRISE INTEGRATION',title:'Real-Time Enterprise CDC & Event-Driven Integration Platform',intro:'Reusable event streams that decouple source systems from enterprise consumers.',metric:'7',metricLabel:'resilient streaming controls',nodes:['Databases / APIs','Debezium / Kafka','Flink / Spark','Delta / Snowflake'],problem:'Batch-dependent integration constrained data freshness and coupled source systems to downstream consumers.',work:'Architected CDC across relational databases, APIs, SaaS applications and legacy systems using Debezium, Kafka Connect, Kafka, Flink and Spark Structured Streaming.',result:'Supported operational analytics, enterprise applications and governed data products with near-real-time delivery and recovery without full pipeline reloads.',controls:'Schema evolution, idempotency, event-time handling, checkpointing, replay, dead-letter queues and reconciliation. Monitored lag, latency, freshness, failed events and schema drift.',tags:['Debezium','Kafka','Flink','OpenTelemetry'],source:'Projects · Real-Time Enterprise CDC'},
 {id:'mesh',kind:'DATA MESH • SELF-SERVICE',title:'Enterprise Data Mesh & Self-Service Data Product Platform',intro:'Domain-owned data products, built on shared enterprise guardrails.',metric:'3',metricLabel:'core platform layers',nodes:['Domain sources','Bronze / Silver / Gold','Catalog / Policies','Certified products'],problem:'Enterprise domains needed independent data-product delivery with consistent ownership, quality and governance.',work:'Designed reusable product patterns using Databricks, Snowflake, dbt and Airflow. Standardized data contracts, quality SLAs, schema evolution and publishing workflows.',result:'Enabled domain teams to independently publish and consume governed data products, reducing dependency on centralized engineering and accelerating self-service analytics.',controls:'Unity Catalog, Collibra and OpenLineage support metadata, enterprise cataloging, policy-based access and end-to-end lineage.',tags:['Databricks','Snowflake','dbt','Airflow'],source:'Projects · Enterprise Data Mesh'},
 {id:'ai',kind:'GOVERNED AI • ENTERPRISE RETRIEVAL',title:'AI-Ready Governed Enterprise Data Access Platform',intro:'Enterprise context for AI assistants, with permissions preserved.',metric:'4',metricLabel:'layers of data protection',nodes:['Data / Documents','Chunk / Embed','Permission-aware search','Grounded context'],problem:'AI assistants needed unified access to structured data, documents and metadata without bypassing enterprise security.',work:'Built permission-aware RAG workflows with MCP, LangChain/LangGraph, Snowflake Cortex and vector search. Designed chunking, embedding, metadata enrichment, hybrid search and grounding.',result:'Enabled multiple AI applications to consume governed enterprise context through reusable access patterns with evidence citations, traceability and human-review controls.',controls:'Unity Catalog governance, RBAC, row-level security and sensitive-data controls protect LLM context while retaining lineage and auditability.',tags:['MCP','LangGraph','RAG','Snowflake Cortex'],source:'Projects · AI-Ready Governed Enterprise Data Access'}
];
export const certifications=['Databricks Certified Data Engineer Associate','Microsoft Fabric Data Engineer Associate','AWS Certified Data Engineer Associate','AWS Well-Architected Framework','Snowflake SnowPro Certification'];
